services:
  - type: web
    name: tarefas
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput --clear
  # Usamos start.sh para detectar automaticamente o m√≥dulo WSGI correto
  startCommand: bash start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: "3.13"
      - key: DB_PATH
        value: "/var/data/db.sqlite3"
    disk:
      name: sqlite_data
      mountPath: /var/data
      sizeGB: 1
